fixed_frame: /bravo_base_link
camera_frame: /zed_left_camera_optical_frame
camera_offset:
  translation: [0.0, 0.0, 0.0]
  rotation:    [0.0, 0.0, 0.0, 1.0]
# There is one entry for each URDF that should be filtered
models:
- model: "robot_description"
  tf_prefix: ""
  geometry_type: "collision" # "visual" or "collision"
  scale: 1.05
  ignore: ["raven_bounding_box", "floor_plane", "zed_camera_center"]
# how far in front of the robot model is still deleted? (e.g. 0.05 = 5cm)
depth_distance_threshold: 0.05
show_gui: False
filter_replace_value: 5
